ALL_YEARS = range(1994, 2019)

US_DATA_PATH = "../US-data"

US_INPUT_PATH = f"{US_DATA_PATH}/unzipped"
US_ORIGINAL_PATH = f"{US_DATA_PATH}/0_original"
US_XML_PATH = f"{US_DATA_PATH}/1_xml"
US_REFERENCE_AREAS_PATH = f"{US_DATA_PATH}/2_reference_areas"
US_REFERENCE_PARSED_PATH = f"{US_DATA_PATH}/3_reference_parsed"
US_HIERARCHY_GRAPH_PATH = f"{US_DATA_PATH}/4_hierarchy_graph"
US_CROSSREFERENCE_LOOKUP_PATH = f"{US_DATA_PATH}/5_crossreference_lookup"
US_CROSSREFERENCE_EDGELIST_PATH = f"{US_DATA_PATH}/6_crossreference_edgelist"
US_CROSSREFERENCE_GRAPH_PATH = f"{US_DATA_PATH}/7_crossreference_graph"
US_SNAPSHOT_MAPPING_EDGELIST_PATH = f"{US_DATA_PATH}/8_snapshot_mapping_edgelist"
US_SNAPSHOT_MAPPING_GRAPH_PATH = f"{US_DATA_PATH}/9_snapshot_mapping_graph"

US_HELPERS_PATH = f"{US_DATA_PATH}/helpers"
US_REFERENCE_AREAS_LOG_PATH = f"{US_HELPERS_PATH}/us_extract_reference_areas.log"
US_REFERENCE_PARSED_LOG_PATH = f"{US_HELPERS_PATH}/us_extract_reference_parsed.log"

US_CD_PREPROCESSED_GRAPH_PATH = f"{US_DATA_PATH}/cd_1_preprocessed_graph"
US_CD_CLUSTER_PATH = f"{US_DATA_PATH}/cd_2_cluster_results"
US_CD_CLUSTER_TEXTS_PATH = f"{US_DATA_PATH}/cd_3_cluster_texts"
US_CD_CLUSTER_MAPPED_PATH = f"{US_DATA_PATH}/cd_4_cluster_evolution_graph"
US_CD_CLUSTER_STATISTICS_PATH = f"{US_DATA_PATH}/cd_5_cluster_statistics"
US_CD_CLUSTER_MAPS_PATH = f"{US_DATA_PATH}/cd_6_cluster_maps"
US_CD_CLUSTER_LABELING_PATH = f"{US_DATA_PATH}/cd_7_cluster_labeling"


DE_DATA_PATH = "../DE-data"
DE_HELPERS_PATH = f"{DE_DATA_PATH}/helpers"
DE_INPUT_PATH = f"{DE_DATA_PATH}/juris-laws"
DE_INPUT_LIST_PATH = f"{DE_HELPERS_PATH}/juris-links.csv"
DE_ORIGINAL_PATH = f"{DE_DATA_PATH}/0_original"
DE_ORIGINAL_VERSION_INDICES_PATH = f"{DE_DATA_PATH}/0a_original_version_indices"
DE_XML_PATH = f"{DE_DATA_PATH}/1_xml"
DE_XML_HEADING_ORDERS_PATH = f"{DE_DATA_PATH}/2_heading_orders.txt"
DE_XML_NESTED_PATH = f"{DE_DATA_PATH}/3_xml_nested"
DE_LAW_NAMES_PATH = f"{DE_DATA_PATH}/4_law_names.csv"
DE_REFERENCE_AREAS_PATH = f"{DE_DATA_PATH}/5_reference_areas"
DE_REFERENCE_PARSED_PATH = f"{DE_DATA_PATH}/6_reference_parsed"
DE_HIERARCHY_GRAPH_PATH = f"{DE_DATA_PATH}/7_hierarchy_graph"
DE_LAW_VALIDITIES_PATH = (
    f"{DE_DATA_PATH}/8_validities.csv"
)  # TODO later renumber to place after law_names
DE_CROSSREFERENCE_LOOKUP_PATH = f"{DE_DATA_PATH}/9_crossreference_lookup"
DE_CROSSREFERENCE_EDGELIST_PATH = f"{DE_DATA_PATH}/10_crossreference_edgelist"
DE_CROSSREFERENCE_GRAPH_PATH = f"{DE_DATA_PATH}/11_crossreference_graph"
DE_SNAPSHOT_MAPPING_EDGELIST_PATH = f"{DE_DATA_PATH}/12_snapshot_mapping_edgelist"

DE_REFERENCE_AREAS_LOG_PATH = f"{DE_HELPERS_PATH}/de_extract_reference_areas.log"
DE_REFERENCE_PARSED_LOG_PATH = f"{DE_HELPERS_PATH}/de_extract_reference_parsed.log"

DE_CD_PREPROCESSED_GRAPH_PATH = f"{DE_DATA_PATH}/cd_1_preprocessed_graph"
DE_CD_CLUSTER_PATH = f"{DE_DATA_PATH}/cd_2_cluster_results"
DE_CD_CLUSTER_TEXTS_PATH = f"{DE_DATA_PATH}/cd_3_cluster_texts"
DE_CD_CLUSTER_MAPPED_PATH = f"{DE_DATA_PATH}/cd_4_cluster_evolution_graph"
DE_CD_CLUSTER_STATISTICS_PATH = f"{DE_DATA_PATH}/cd_5_cluster_statistics"
DE_CD_CLUSTER_MAPS_PATH = f"{DE_DATA_PATH}/cd_6_cluster_maps"
DE_CD_CLUSTER_LABELING_PATH = f"{DE_DATA_PATH}/cd_7_cluster_labeling"
